# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NovoUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastro(object):
    def setupUi(self, Cadastro):
        Cadastro.setObjectName("Cadastro")
        Cadastro.resize(151, 131)
        self.centralwidget = QtWidgets.QWidget(Cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.Usuario.setObjectName("Usuario")
        self.gridLayout.addWidget(self.Usuario, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.senha = QtWidgets.QLineEdit(self.centralwidget)
        self.senha.setObjectName("senha")
        self.gridLayout.addWidget(self.senha, 3, 0, 1, 1)
        self.Salvar = QtWidgets.QPushButton(self.centralwidget)
        self.Salvar.setObjectName("Salvar")
        self.gridLayout.addWidget(self.Salvar, 4, 0, 1, 1)
        Cadastro.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cadastro)
        QtCore.QMetaObject.connectSlotsByName(Cadastro)

    def retranslateUi(self, Cadastro):
        _translate = QtCore.QCoreApplication.translate
        Cadastro.setWindowTitle(_translate("Cadastro", "MainWindow"))
        self.label.setText(_translate("Cadastro", "Usuário"))
        self.label_2.setText(_translate("Cadastro", "Senha"))
        self.Salvar.setText(_translate("Cadastro", "Salvar"))
